"""邮件通知服务。

提供系统内置的邮件 HTML 模板构建与发送能力。
当前支持策略通知邮件与密码重置验证码邮件。
"""

import html
import logging
from typing import Literal

from pydantic import BaseModel, Field

from app.services.notification.i18n_templates import get_direction_label

logger = logging.getLogger(__name__)


# ── Pydantic 数据模型 ─────────────────────────────────────────


class StrategyEmailData(BaseModel):
    """策略邮件数据模型，用于构建 HTML 邮件内容。"""

    symbol: str = Field(..., description="交易对，如 BTCUSDT")
    direction: Literal["bullish", "bearish", "neutral"] = Field(
        ..., description="策略方向"
    )
    entry_low: float = Field(..., description="入场区间下限")
    entry_high: float = Field(..., description="入场区间上限")
    stop_loss: float = Field(..., description="止损价")
    targets: list[float] = Field(default_factory=list, description="目标价列表")
    confidence: float = Field(..., ge=0.0, le=1.0, description="置信度 0-1")
    reasoning: str = Field(default="", description="策略推理摘要")
    locale: str = Field(default="zh-CN", description="用户语言偏好")


class ResetCodeEmailData(BaseModel):
    """密码重置验证码邮件数据模型。"""

    code: str = Field(..., min_length=6, max_length=6, description="6位验证码")
    locale: str = Field(default="zh-CN", description="用户语言偏好")


class RegisterCodeEmailData(BaseModel):
    """注册验证码邮件数据模型。"""

    code: str = Field(..., min_length=6, max_length=6, description="6位验证码")
    locale: str = Field(default="zh-CN", description="用户语言偏好")


# ── 颜色常量 ──────────────────────────────────────────────────

_COLOR_MAP: dict[str, dict[str, str]] = {
    "bullish": {
        "accent": "#00F5A0",
        "bg_gradient": "linear-gradient(135deg, rgba(0,245,160,0.15), rgba(0,245,160,0.03))",
    },
    "bearish": {
        "accent": "#FF3B6F",
        "bg_gradient": "linear-gradient(135deg, rgba(255,59,111,0.15), rgba(255,59,111,0.03))",
    },
    "neutral": {
        "accent": "#2A6DFF",
        "bg_gradient": "linear-gradient(135deg, rgba(42,109,255,0.15), rgba(42,109,255,0.03))",
    },
}

_DIRECTION_EMOJI: dict[str, str] = {
    "bullish": "📈",
    "bearish": "📉",
    "neutral": "⏸",
}

_STRATEGY_EMAIL_STRINGS: dict[str, dict[str, str]] = {
    "zh-CN": {
        "subtitle": "多智能体博弈共识分析系统",
        "entry_range": "🎯 入场区间",
        "stop_loss": "🛑 止损",
        "targets": "🏁 目标",
        "confidence": "📊 置信度",
        "analysis_summary": "💡 分析摘要",
        "no_analysis": "暂无详细分析",
        "footer": "本邮件由 Axiom 系统自动生成，仅供参考，不构成投资建议。<br>如需退订，请在设置页面关闭邮件推送。",
    },
    "zh-TW": {
        "subtitle": "多智能體博弈共識分析系統",
        "entry_range": "🎯 入場區間",
        "stop_loss": "🛑 止損",
        "targets": "🏁 目標",
        "confidence": "📊 置信度",
        "analysis_summary": "💡 分析摘要",
        "no_analysis": "暫無詳細分析",
        "footer": "本郵件由 Axiom 系統自動生成，僅供參考，不構成投資建議。<br>如需退訂，請在設置頁面關閉郵件推送。",
    },
    "en": {
        "subtitle": "Multi-Agent Consensus Analysis System",
        "entry_range": "🎯 Entry Range",
        "stop_loss": "🛑 Stop Loss",
        "targets": "🏁 Targets",
        "confidence": "📊 Confidence",
        "analysis_summary": "💡 Analysis Summary",
        "no_analysis": "No detailed analysis available",
        "footer": "This email is automatically generated by Axiom. For reference only, not investment advice.<br>To unsubscribe, disable email notifications in settings.",
    },
}

_RESET_CODE_EMAIL_STRINGS: dict[str, dict[str, str]] = {
    "zh-CN": {
        "subject": "[Axiom] 密码重置验证码",
        "title": "密码重置验证码",
        "hint": "验证码 10 分钟内有效。如果不是您本人操作，请忽略此邮件。",
    },
    "zh-TW": {
        "subject": "[Axiom] 密碼重置驗證碼",
        "title": "密碼重置驗證碼",
        "hint": "驗證碼 10 分鐘內有效。如果不是您本人操作，請忽略此郵件。",
    },
    "en": {
        "subject": "[Axiom] Password Reset Code",
        "title": "Password Reset Code",
        "hint": "The code expires in 10 minutes. If you did not request this, please ignore this email.",
    },
}

_REGISTER_CODE_EMAIL_STRINGS: dict[str, dict[str, str]] = {
    "zh-CN": {
        "subject": "[Axiom] 注册验证码",
        "title": "注册验证码",
        "hint": "验证码 10 分钟内有效。若非本人操作，请忽略此邮件。",
    },
    "zh-TW": {
        "subject": "[Axiom] 註冊驗證碼",
        "title": "註冊驗證碼",
        "hint": "驗證碼 10 分鐘內有效。若非本人操作，請忽略此郵件。",
    },
    "en": {
        "subject": "[Axiom] Registration Code",
        "title": "Registration Code",
        "hint": "The code expires in 10 minutes. If this was not you, please ignore this email.",
    },
}


def _get_localized_strings(
    locale: str,
    strings_map: dict[str, dict[str, str]],
) -> dict[str, str]:
    """按 locale 获取邮件本地化字符串。"""
    if locale in strings_map:
        return strings_map[locale]
    if locale.startswith("zh"):
        return strings_map["zh-CN"]
    return strings_map["en"]


def _get_html_lang(locale: str) -> str:
    """将 locale 转换为 HTML lang 属性值。"""
    return {"zh-CN": "zh-CN", "zh-TW": "zh-TW", "en": "en"}.get(locale, "en")


# ── HTML 模板构建 ─────────────────────────────────────────────


def _format_price(price: float) -> str:
    """格式化价格，保留合理小数位。"""
    if price >= 1000:
        return f"{price:,.2f}"
    if price >= 1:
        return f"{price:.4f}"
    return f"{price:.8f}"


def _build_confidence_stars(confidence: float) -> str:
    """将 0-1 置信度转换为星级 HTML。"""
    stars = round(confidence * 5)
    filled = "★" * stars
    empty = "☆" * (5 - stars)
    return f"{filled}{empty}"


def _build_targets_html(targets: list[float], accent: str) -> str:
    """构建目标价列表 HTML。"""
    if not targets:
        return '<span style="color:#666;">—</span>'
    items: list[str] = []
    for i, t in enumerate(targets, 1):
        items.append(
            f'<span style="color:{accent};font-family:\'Roboto Mono\',monospace;">'
            f"T{i}: {_format_price(t)}</span>"
        )
    return " → ".join(items)


def build_strategy_html(data: StrategyEmailData) -> str:
    """根据策略数据构建科技风 HTML 邮件内容。

    Args:
        data: 策略邮件数据（pydantic 模型）

    Returns:
        完整的 HTML 邮件字符串
    """
    locale = data.locale
    s = _get_localized_strings(locale, _STRATEGY_EMAIL_STRINGS)
    html_lang = _get_html_lang(locale)
    colors = _COLOR_MAP.get(data.direction, _COLOR_MAP["neutral"])
    accent = colors["accent"]
    bg_gradient = colors["bg_gradient"]
    dir_emoji = _DIRECTION_EMOJI.get(data.direction, "⏸")
    dir_label = get_direction_label(data.direction, locale)
    label = f"{dir_emoji} {dir_label}"
    confidence_pct = f"{data.confidence:.0%}"
    stars_html = _build_confidence_stars(data.confidence)
    targets_html = _build_targets_html(data.targets, accent)

    return f"""\
<!DOCTYPE html>
<html lang="{html_lang}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#0A0F1B;font-family:'Segoe UI',Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0A0F1B;padding:20px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

  <!-- Header -->
  <tr><td style="padding:24px 32px;text-align:center;">
    <span style="font-size:24px;font-weight:700;color:#2A6DFF;letter-spacing:2px;">⚡ Axiom</span>
    <div style="color:#555;font-size:12px;margin-top:4px;letter-spacing:1px;">{s['subtitle']}</div>
  </td></tr>

  <!-- Direction Banner -->
  <tr><td style="padding:0 24px;">
    <div style="background:{bg_gradient};border:1px solid {accent}33;border-radius:12px;padding:20px 24px;text-align:center;">
      <div style="font-size:28px;font-weight:700;color:{accent};letter-spacing:3px;">{label}</div>
      <div style="color:#888;font-size:14px;margin-top:6px;font-family:'Roboto Mono',monospace;">{data.symbol}</div>
    </div>
  </td></tr>

  <!-- Strategy Details -->
  <tr><td style="padding:16px 24px 0;">
    <table width="100%" cellpadding="0" cellspacing="0"
           style="background:rgba(255,255,255,0.04);border:1px solid rgba(42,109,255,0.15);border-radius:10px;">
      <!-- Entry Range -->
      <tr>
        <td style="padding:16px 20px 8px;color:#888;font-size:13px;">{s['entry_range']}</td>
        <td style="padding:16px 20px 8px;text-align:right;color:#E0E0E0;font-family:'Roboto Mono',monospace;font-size:15px;">
          {_format_price(data.entry_low)} ~ {_format_price(data.entry_high)}
        </td>
      </tr>
      <!-- Stop Loss -->
      <tr>
        <td style="padding:8px 20px;color:#888;font-size:13px;">{s['stop_loss']}</td>
        <td style="padding:8px 20px;text-align:right;color:#FF3B6F;font-family:'Roboto Mono',monospace;font-size:15px;">
          {_format_price(data.stop_loss)}
        </td>
      </tr>
      <!-- Targets -->
      <tr>
        <td style="padding:8px 20px;color:#888;font-size:13px;">{s['targets']}</td>
        <td style="padding:8px 20px;text-align:right;font-size:14px;">{targets_html}</td>
      </tr>
      <!-- Confidence -->
      <tr>
        <td style="padding:8px 20px 16px;color:#888;font-size:13px;">{s['confidence']}</td>
        <td style="padding:8px 20px 16px;text-align:right;">
          <span style="color:{accent};font-size:18px;letter-spacing:2px;">{stars_html}</span>
          <span style="color:#E0E0E0;font-family:'Roboto Mono',monospace;margin-left:8px;">{confidence_pct}</span>
        </td>
      </tr>
    </table>
  </td></tr>

  <!-- Reasoning -->
  <tr><td style="padding:16px 24px 0;">
    <div style="background:rgba(255,255,255,0.03);border:1px solid rgba(42,109,255,0.1);border-radius:10px;padding:16px 20px;">
      <div style="color:#2A6DFF;font-size:13px;font-weight:600;margin-bottom:8px;">{s['analysis_summary']}</div>
      <div style="color:#AAAAAA;font-size:13px;line-height:1.7;">{html.escape(data.reasoning) if data.reasoning else s['no_analysis']}</div>
    </div>
  </td></tr>

  <!-- Footer -->
  <tr><td style="padding:24px 32px;text-align:center;">
    <div style="color:#444;font-size:11px;line-height:1.6;">
      {s['footer']}
    </div>
  </td></tr>

</table>
</td></tr>
</table>
</body>
</html>"""


def build_reset_code_html(data: ResetCodeEmailData) -> str:
    """构建密码重置验证码邮件 HTML。"""
    html_lang = _get_html_lang(data.locale)
    s = _get_localized_strings(data.locale, _RESET_CODE_EMAIL_STRINGS)

    return f"""\
<!DOCTYPE html>
<html lang="{html_lang}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0A0F1B;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0A0F1B;padding:24px 0;">
    <tr><td align="center">
      <table width="420" cellpadding="0" cellspacing="0" style="max-width:420px;width:100%;background:#131316;border-radius:12px;border:1px solid rgba(255,255,255,0.08);padding:24px;">
        <tr><td style="text-align:center;">
          <div style="font-size:22px;font-weight:700;color:#2A6DFF;letter-spacing:1px;">⚡ Axiom</div>
          <h2 style="color:#e4e4e7;font-size:18px;margin:16px 0 12px;">{s['title']}</h2>
          <div style="background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);border-radius:8px;padding:16px;text-align:center;margin:0 0 16px;">
            <span style="font-size:32px;letter-spacing:8px;font-weight:700;color:#818cf8;font-family:monospace;">{html.escape(data.code)}</span>
          </div>
          <p style="color:#a1a1aa;font-size:13px;line-height:1.7;margin:0;">{s['hint']}</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


def build_register_code_html(data: RegisterCodeEmailData) -> str:
    """构建注册验证码邮件 HTML。"""
    html_lang = _get_html_lang(data.locale)
    s = _get_localized_strings(data.locale, _REGISTER_CODE_EMAIL_STRINGS)

    return f"""\
<!DOCTYPE html>
<html lang="{html_lang}">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0A0F1B;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0A0F1B;padding:24px 0;">
    <tr><td align="center">
      <table width="420" cellpadding="0" cellspacing="0" style="max-width:420px;width:100%;background:#131316;border-radius:12px;border:1px solid rgba(255,255,255,0.08);padding:24px;">
        <tr><td style="text-align:center;">
          <div style="font-size:22px;font-weight:700;color:#2A6DFF;letter-spacing:1px;">⚡ Axiom</div>
          <h2 style="color:#e4e4e7;font-size:18px;margin:16px 0 12px;">{s['title']}</h2>
          <div style="background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);border-radius:8px;padding:16px;text-align:center;margin:0 0 16px;">
            <span style="font-size:32px;letter-spacing:8px;font-weight:700;color:#818cf8;font-family:monospace;">{html.escape(data.code)}</span>
          </div>
          <p style="color:#a1a1aa;font-size:13px;line-height:1.7;margin:0;">{s['hint']}</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


# ── 邮件发送底层 ──────────────────────────────────────────────

_DEFAULT_FROM = "noreply@axiom123.cc"


async def _get_email_provider() -> tuple[str, str] | None:
    """获取可用的邮件服务商和 API Key。

    优先级: resend_api_key > sendgrid_api_key
    返回 (provider, api_key) 或 None。
    """
    from app.services.config_service import get_config_value

    resend_key = await get_config_value("resend_api_key")
    if resend_key:
        return ("resend", resend_key)

    sendgrid_key = await get_config_value("sendgrid_api_key")
    if sendgrid_key:
        return ("sendgrid", sendgrid_key)

    return None


async def _send_via_resend(
    api_key: str, from_email: str, to_email: str, subject: str, html_content: str
) -> bool:
    """通过 Resend API 发送邮件。"""
    import resend
    import asyncio as _aio
    resend.api_key = api_key
    last_exc = None
    for attempt in range(3):
        try:
            resp = resend.Emails.send({
                "from": from_email,
                "to": [to_email],
                "subject": subject,
                "html": html_content,
            })
            email_id = resp.get("id") if isinstance(resp, dict) else getattr(resp, "id", None)
            logger.info("Email sent via Resend", extra={"to": to_email, "id": email_id})
            return True
        except Exception as exc:
            last_exc = exc
            if attempt < 2:
                await _aio.sleep(1 * (attempt + 1))
    logger.exception("Failed to send email via Resend after 3 attempts", extra={"to": to_email})
    return False


async def _send_via_sendgrid(
    api_key: str, from_email: str, to_email: str, subject: str, html_content: str
) -> bool:
    """通过 SendGrid API 发送邮件（向后兼容）。"""
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail

        message = Mail(
            from_email=from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content,
        )
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        logger.info("Email sent via SendGrid", extra={"to": to_email, "status": response.status_code})
        return response.status_code in (200, 201, 202)
    except Exception:
        logger.exception("Failed to send email via SendGrid", extra={"to": to_email})
        return False


async def _is_suppressed(email: str) -> bool:
    """检查邮箱是否在抑制列表中（退信/投诉过）。"""
    try:
        from app.core.database import get_db_context
        from sqlalchemy import text as sa_text
        async with get_db_context() as session:
            result = await session.execute(
                sa_text("SELECT 1 FROM email_suppression WHERE email = :email"),
                {"email": email.lower().strip()},
            )
            return result.first() is not None
    except Exception:
        return False


async def _dispatch_email(
    to_email: str, subject: str, html_content: str, from_email: str = _DEFAULT_FROM
) -> bool:
    """统一邮件分发——自动选择可用的服务商。"""
    if await _is_suppressed(to_email):
        logger.info("Email to %s suppressed (bounced/complained), skipping", to_email)
        return False

    provider = await _get_email_provider()
    if provider is None:
        logger.warning("No email provider configured (set resend_api_key or sendgrid_api_key), skipping email")
        return False

    name, api_key = provider
    if name == "resend":
        return await _send_via_resend(api_key, from_email, to_email, subject, html_content)
    return await _send_via_sendgrid(api_key, from_email, to_email, subject, html_content)


# ── 业务层邮件接口（对外不变） ────────────────────────────────


async def send_strategy_email(
    to_email: str,
    strategy_data: StrategyEmailData,
) -> bool:
    """构建策略 HTML 并发送邮件。"""
    html_content = build_strategy_html(strategy_data)
    dir_label = get_direction_label(strategy_data.direction, strategy_data.locale)
    _subject_prefix = {
        "zh-CN": "策略更新",
        "zh-TW": "策略更新",
        "en": "Strategy Update",
    }
    locale = strategy_data.locale
    prefix = _subject_prefix.get(locale, _subject_prefix["en"])
    subject = f"[Axiom] {strategy_data.symbol} {prefix} — {dir_label}"
    return await _dispatch_email(to_email, subject, html_content)


async def send_reset_code_email(
    to_email: str,
    reset_data: ResetCodeEmailData,
) -> bool:
    """构建密码重置验证码 HTML 并发送邮件。"""
    html_content = build_reset_code_html(reset_data)
    s = _get_localized_strings(reset_data.locale, _RESET_CODE_EMAIL_STRINGS)
    subject = s["subject"]
    return await _dispatch_email(to_email, subject, html_content)


async def send_register_code_email(
    to_email: str,
    register_data: RegisterCodeEmailData,
) -> bool:
    """构建注册验证码 HTML 并发送邮件。"""
    html_content = build_register_code_html(register_data)
    s = _get_localized_strings(register_data.locale, _REGISTER_CODE_EMAIL_STRINGS)
    subject = s["subject"]
    return await _dispatch_email(to_email, subject, html_content)


async def send_raw_email(
    to_email: str,
    subject: str,
    html_content: str,
) -> bool:
    """发送自定义 HTML 邮件（通用接口）。"""
    return await _dispatch_email(to_email, subject, html_content)
